security:
  # Hashing des mots de passe
  password_hashers:
    App\Entity\User: 'auto'

  # Provider basé sur l'entité User
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # Firewalls
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\AppLoginAuthenticator
      logout:
        path: app_logout
        target: /login
      # activer la session
      # form_login est géré par l’authenticator

  # Contrôle d’accès selon les rôles
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/emprunt, roles: [ ROLE_LIBRARIAN, ROLE_ADMIN ] }
    - { path: ^/reservation, roles: [ ROLE_MEMBER, ROLE_ADMIN ] }


# Configuration spécifique pour les tests
when@test:
  security:
    password_hashers:
      App\Entity\User:
        algorithm: auto
        cost: 4
